<a href="https://colab.research.google.com/github/elichen/aoc2021/blob/main/Day_20_Trench_Map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
input = '''..#.#..#####.#.#.#.###.##.....###.##.#..###.####..#####..#....#..#..##..###..######.###...####..#..#####..##..#.#####...##.#.#..#.##..#.#......#.###.######.###.####...#.##.##..#..#..#####.....#.#....###..#.##......#.....#..#..#..##..#...##.######.####.####.#.#...#.......#..#.#.#...####.##.#......#..#...##.#.##..#...##.#.##..###.#......#.#.......#.#.#.####.###.##...#.....####.#..#..#.##.#....##..#.####....##...##..#...#......#.#.......#.......##..####..#...#.#.#...##..#.#..###..#####........#..####......#..#

#..#.
#....
##..#
..#..
..###'''.split('\n')

In [ ]:
input = open("input.txt").readlines()
input = [x.rstrip() for x in input]

In [ ]:
alg = input[0]

In [ ]:
import numpy as np
img = []
for line in input[2:]:
  img.append(np.array([c == '#' for c in line],dtype=int))
img = np.array(img)

for i in range(50):
  rows,cols = img.shape
  img = np.pad(img, pad_width=2, mode='constant', constant_values=1 if alg[0] == '#' and i%2 == 1 else 0)
  new_img = np.zeros((rows+2,cols+2),dtype=int)
  for row in range(rows+2):
    for col in range(cols+2):
      idx = int("".join(__builtin__.map(str,img[row:row+3,col:col+3].flatten().tolist())),2)
      new_img[row,col] = 1 if alg[idx] == '#' else 0
  img = new_img
  print(img, img.shape, np.count_nonzero(img))

[[1 0 1 ... 1 1 1]
 [1 0 0 ... 1 0 1]
 [1 0 1 ... 1 1 1]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [1 0 1 ... 1 0 1]] (102, 102) 5232
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 1 0 0]
 ...
 [1 0 1 ... 0 1 0]
 [0 1 0 ... 1 0 1]
 [0 0 1 ... 1 1 0]] (104, 104) 5218
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 0 ... 1 1 1]
 ...
 [0 0 1 ... 0 1 1]
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 1]] (106, 106) 5876
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 1 1 ... 0 0 0]
 [0 0 1 ... 0 0 1]
 [0 0 0 ... 0 1 0]] (108, 108) 5574
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 0 1 ... 1 0 1]
 [1 1 0 ... 1 0 0]
 [1 1 1 ... 1 0 1]] (110, 110) 6366
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 1 1 0]] (112, 112) 5989
[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 0 0 1]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 1]] (114, 114) 6966
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ..